---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _data
  label: Data
  create: documents
  match: "*.yml"
  new_doc_ext: yml
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
